const hostname="https://adarsh-cart-server.herokuapp.com/"
export const homeProductURL=hostname+"home_products"
export const searchProductURL=hostname+"search_products"
export const categoryProductURL=hostname+"category/"
export const allProductURL=hostname+"all_products"
export const cartProductURL=hostname+"cart_products"
export const cartUpdateURL=hostname+"cart_update"
export const reviewURL=hostname+"review"
export const shoppingInfoSendURL=hostname+'shop'