const hostname="http://192.168.2.12:5000/"
export const homeProductURL=hostname+"home_products"
export const allProductURL=hostname+"all_products"
export const cartProductURL=hostname+"cart_products"
export const cartUpdateURL=hostname+"cart_update"
